name: "Deploy stage"

on:
  workflow_run:
      workflows: ["Run tests"]
      branches: [ stage ]
      types:
        - completed

jobs:
  deploy-master:
    runs-on: [ self-hosted, qa ]
    strategy:
        matrix:
          node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to stage server
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
